[package]
name = "raffia_macro"
version = "0.2.0"
edition = "2024"
authors = ["Pig Fang <g-plane@hotmail.com>"]
description = "Macros for Raffia."
repository = "https://github.com/g-plane/raffia"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
heck = "0.5"
quote = "1.0"
syn = "2.0"
